#pragma once
#include <iostream>
#include <bitset>
#include <string>
#include <fstream>
#include <vector>
#include <array>
#include <functional>
#include <Windows.h>
#include <windowsx.h>
#include <memory>
#include <chrono>
